name: Deployment
concurrency:
  group: production
  cancel-in-progress: true
on: [workflow_dispatch]
jobs:
  deployment:
   runs-on: ubuntu-latest
   environment: production
   steps:
    - uses: actions/checkout@v3
    - name: deploy
      run: ./deploy/deploy.sh