name: Deployment
concurrency:
  group: production
  cancel-in-progress: true
on: [workflow_run]
jobs:
  deployment:
   runs-on: ubuntu-latest
   environment: production
   steps:
    - name: deploy
      run: ./deploy/deploy.sh